CREATE TABLE [dbo].[BC_Temp] (
    [ID]                                                           INT            IDENTITY (1, 1) NOT NULL,
    [FolioRecord_ID]                                               VARCHAR (100)  NULL,
    [RollYear]                                                     INT            NULL,
    [AssessmentAreaDescription]                                    NVARCHAR (MAX) NULL,
    [JurisdictionCode]                                             NVARCHAR (MAX) NULL,
    [JurisdictionDescription]                                      NVARCHAR (MAX) NULL,
    [RollNumber]                                                   NVARCHAR (MAX) NULL,
    [ActualUseDescription]                                         NVARCHAR (MAX) NULL,
    [VacantFlag]                                                   NVARCHAR (MAX) NULL,
    [TenureDescription]                                            NVARCHAR (MAX) NULL,
    [FolioAddresses_FolioAddress_City]                             NVARCHAR (MAX) NULL,
    [FolioAddresses_FolioAddress_ID]                               VARCHAR (100)  NULL,
    [FolioAddresses_FolioAddress_PostalZip]                        NVARCHAR (MAX) NULL,
    [FolioAddresses_FolioAddress_PrimaryFlag]                      NVARCHAR (MAX) NULL,
    [FolioAddresses_FolioAddress_ProvinceState]                    NVARCHAR (MAX) NULL,
    [FolioAddresses_FolioAddress_StreetDirectionSuffix]            NVARCHAR (MAX) NULL,
    [FolioAddresses_FolioAddress_StreetName]                       NVARCHAR (MAX) NULL,
    [FolioAddresses_FolioAddress_StreetNumber]                     NVARCHAR (MAX) NULL,
    [FolioAddresses_FolioAddress_StreetType]                       NVARCHAR (MAX) NULL,
    [FolioAddresses_FolioAddress_UnitNumber]                       NVARCHAR (MAX) NULL,
    [LandMeasurement_LandDepth]                                    NVARCHAR (MAX) NULL,
    [LandMeasurement_LandDimension]                                NVARCHAR (MAX) NULL,
    [LandMeasurement_LandDimensionTypeDescription]                 NVARCHAR (MAX) NULL,
    [LandMeasurement_LandWidth]                                    NVARCHAR (MAX) NULL,
    [FolioDescription_Neighbourhood_NeighbourhoodCode]             NVARCHAR (MAX) NULL,
    [FolioDescription_Neighbourhood_NeighbourhoodDescription]      NVARCHAR (MAX) NULL,
    [RegionalDistrict_DistrictDescription]                         NVARCHAR (MAX) NULL,
    [SchoolDistrict_DistrictDescription]                           NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_Block]                     NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_DistrictLot]               NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_ExceptPlan]                NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_FormattedLegalDescription] NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_ID]                        VARCHAR (100)  NULL,
    [LegalDescriptions_LegalDescription_LandDistrict]              NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_LandDistrictDescription]   NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_LeaseLicenceNumber]        NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_LegalText]                 NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_Lot]                       NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_Meridian]                  NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_MeridianShort]             NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_Parcel]                    NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_Part1]                     NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_Part2]                     NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_Part3]                     NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_Part4]                     NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_PID]                       NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_Plan]                      NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_Portion]                   NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_Range]                     NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_Section]                   NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_StrataLot]                 NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_SubBlock]                  NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_SubLot]                    NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_LegalSubdivision]          NVARCHAR (MAX) NULL,
    [LegalDescriptions_LegalDescription_Township]                  NVARCHAR (MAX) NULL,
    [Sales_Sale_ConveyanceDate]                                    NVARCHAR (MAX) NULL,
    [Sales_Sale_ConveyancePrice]                                   NVARCHAR (MAX) NULL,
    [Sales_Sale_ID]                                                VARCHAR (100)  NULL,
    [HashBytes]                                                    BINARY (64)    NULL,
    [DateCreatedUTC]                                               DATETIME       NULL,
    [LastModifiedDateUTC]                                          DATETIME       NULL,
    [Code]                                                         VARCHAR (200)  NULL
);

