CREATE TABLE [StageProcessing].[ALL_TestAddressFields] (
    [SourceID]                  INT           NULL,
    [Code]                      VARCHAR (200) NULL,
    [UnitNumber]                VARCHAR (100) NULL,
    [StreetNumber]              VARCHAR (100) NULL,
    [StreetName]                VARCHAR (200) NULL,
    [StreetType]                VARCHAR (200) NULL,
    [StreetDirection]           VARCHAR (20)  NULL,
    [City]                      VARCHAR (200) NULL,
    [ProvinceCode]              VARCHAR (50)  NULL,
    [FSA]                       VARCHAR (3)   NULL,
    [District]                  VARCHAR (100) NULL,
    [JurCode]                   VARCHAR (10)  NULL,
    [Country]                   VARCHAR (30)  NULL,
    [Latitude]                  VARCHAR (50)  NULL,
    [Longitude]                 VARCHAR (50)  NULL,
    [LatitudeLongitude]         VARCHAR (50)  NULL,
    [Neighbourhood]             VARCHAR (100) NULL,
    [NeighbourhoodDescription]  VARCHAR (200) NULL,
    [Municipality]              VARCHAR (100) NULL,
    [Region]                    VARCHAR (50)  NULL,
    [Township]                  VARCHAR (10)  NULL,
    [Range]                     VARCHAR (10)  NULL,
    [LandDistrict]              VARCHAR (10)  NULL,
    [LandDistrictName]          VARCHAR (100) NULL,
    [AreaDescription]           VARCHAR (100) NULL,
    [JurDescription]            VARCHAR (100) NULL,
    [SchoolDistrictDescription] VARCHAR (50)  NULL,
    [CrossStreet]               VARCHAR (100) NULL,
    [Community]                 VARCHAR (100) NULL,
    [IsMunicipalAddress]        VARCHAR (5)   NULL,
    [PostalCode]                VARCHAR (50)  NULL,
    [CompleteDate]              DATE          NULL,
    [POSDateSales]              DATETIME      NULL,
    [ClosingDate]               DATETIME      NULL,
    [HashBytes]                 BINARY (64)   NULL,
    [ActionType]                CHAR (1)      NULL,
    [IsDuplicate]               BIT           NULL
);

