CREATE TABLE [StageProcessing].[BC_ALL_Assessment_rv] (
    [SourceID]                                                          INT             NULL,
    [Code]                                                              VARCHAR (200)   NULL,
    [RollNumber]                                                        VARCHAR (200)   NULL,
    [FolioAddresses_FolioAddress_UnitNumber]                            VARCHAR (100)   NULL,
    [FolioAddresses_FolioAddress_StreetNumber]                          VARCHAR (100)   NULL,
    [FolioAddresses_FolioAddress_StreetName]                            VARCHAR (200)   NULL,
    [FolioAddresses_FolioAddress_StreetType]                            VARCHAR (200)   NULL,
    [FolioAddresses_FolioAddress_City]                                  VARCHAR (200)   NULL,
    [FolioAddresses_FolioAddress_ProvinceState]                         VARCHAR (50)    NULL,
    [FolioAddresses_FolioAddress_PostalZip]                             VARCHAR (50)    NULL,
    [LegalDescriptions_LegalDescription_FormattedLegalDescription]      VARCHAR (4000)  NULL,
    [LegalDescriptions_LegalDescription_PID]                            VARCHAR (50)    NULL,
    [LegalDescriptions_LegalDescription_Plan]                           VARCHAR (100)   NULL,
    [LegalDescriptions_LegalDescription_LandDistrict]                   VARCHAR (10)    NULL,
    [LegalDescriptions_LegalDescription_LandDistrictDescription]        VARCHAR (100)   NULL,
    [FolioDescription_Neighbourhood_NeighbourhoodCode]                  VARCHAR (100)   NULL,
    [FolioDescription_Neighbourhood_NeighbourhoodDescription]           VARCHAR (200)   NULL,
    [ActualUseDescription]                                              VARCHAR (100)   NULL,
    [VacantFlag]                                                        VARCHAR (5)     NULL,
    [TenureDescription]                                                 VARCHAR (100)   NULL,
    [SchoolDistrict_DistrictDescription]                                VARCHAR (50)    NULL,
    [RegionalDistrict_DistrictDescription]                              VARCHAR (50)    NULL,
    [Values_GeneralValues_PropertyClassValues_PropertyClassDescription] VARCHAR (100)   NULL,
    [Valuation_ValuesByETC_LandValue]                                   DECIMAL (17, 2) NULL,
    [Valuation_ValuesByETC_ImprovementValue]                            DECIMAL (17, 2) NULL,
    [AssessmentAreaDescription]                                         VARCHAR (100)   NULL,
    [JurisdictionCode]                                                  VARCHAR (10)    NULL,
    [JurisdictionDescription]                                           VARCHAR (100)   NULL,
    [RollYear]                                                          INT             NULL,
    [Sales_Sale_ConveyanceDate]                                         DATE            NULL,
    [Sales_Sale_ConveyancePrice]                                        DECIMAL (17, 2) NULL,
    [LandMeasurement_LandDimensionTypeDescription]                      VARCHAR (50)    NULL,
    [LandMeasurement_LandDimension]                                     DECIMAL (17, 2) NULL,
    [LandMeasurement_LandWidth]                                         VARCHAR (50)    NULL,
    [LandMeasurement_LandDepth]                                         VARCHAR (50)    NULL,
    [FolioAddresses_FolioAddress_StreetDirectionSuffix]                 VARCHAR (20)    NULL,
    [LegalDescriptions_LegalDescription_Range]                          VARCHAR (10)    NULL,
    [LegalDescriptions_LegalDescription_Township]                       VARCHAR (10)    NULL,
    [HashBytes]                                                         BINARY (64)     NULL,
    [ActionType]                                                        CHAR (1)        NULL,
    [IsDuplicate]                                                       BIT             NULL,
    [LegalDescriptions_LegalDescription_Block]                          NVARCHAR (MAX)  NULL,
    [LegalDescriptions_LegalDescription_DistrictLot]                    NVARCHAR (MAX)  NULL,
    [LegalDescriptions_LegalDescription_ExceptPlan]                     NVARCHAR (MAX)  NULL,
    [LegalDescriptions_LegalDescription_LegalSubdivision]               NVARCHAR (MAX)  NULL,
    [LegalDescriptions_LegalDescription_LegalText]                      NVARCHAR (MAX)  NULL,
    [LegalDescriptions_LegalDescription_Lot]                            NVARCHAR (MAX)  NULL,
    [LegalDescriptions_LegalDescription_Parcel]                         NVARCHAR (MAX)  NULL,
    [LegalDescriptions_LegalDescription_Part1]                          NVARCHAR (MAX)  NULL,
    [LegalDescriptions_LegalDescription_Part2]                          NVARCHAR (MAX)  NULL,
    [LegalDescriptions_LegalDescription_Part3]                          NVARCHAR (MAX)  NULL,
    [LegalDescriptions_LegalDescription_Part4]                          NVARCHAR (MAX)  NULL,
    [LegalDescriptions_LegalDescription_Portion]                        NVARCHAR (MAX)  NULL,
    [LegalDescriptions_LegalDescription_Section]                        NVARCHAR (MAX)  NULL,
    [LegalDescriptions_LegalDescription_StrataLot]                      NVARCHAR (MAX)  NULL,
    [LegalDescriptions_LegalDescription_SubBlock]                       NVARCHAR (MAX)  NULL,
    [LegalDescriptions_LegalDescription_SubLot]                         NVARCHAR (MAX)  NULL
);

