CREATE TABLE [StageProcessing].[BC_Vancouver_property_tax_report_2018] (
    [SourceID]                  INT             NULL,
    [Code]                      VARCHAR (200)   NULL,
    [PID]                       VARCHAR (50)    NULL,
    [LEGAL_TYPE]                VARCHAR (100)   NULL,
    [FOLIO]                     VARCHAR (200)   NULL,
    [ZONE_NAME]                 VARCHAR (400)   NULL,
    [ZONE_CATEGORY]             VARCHAR (400)   NULL,
    [PLAN]                      VARCHAR (100)   NULL,
    [FROM_CIVIC_NUMBER]         VARCHAR (100)   NULL,
    [TO_CIVIC_NUMBER]           VARCHAR (100)   NULL,
    [STREET_NAME]               VARCHAR (200)   NULL,
    [PROPERTY_POSTAL_CODE]      VARCHAR (50)    NULL,
    [NARRATIVE_LEGAL_LINE1]     VARCHAR (4000)  NULL,
    [NARRATIVE_LEGAL_LINE2]     VARCHAR (4000)  NULL,
    [NARRATIVE_LEGAL_LINE3]     VARCHAR (4000)  NULL,
    [NARRATIVE_LEGAL_LINE4]     VARCHAR (4000)  NULL,
    [NARRATIVE_LEGAL_LINE5]     VARCHAR (4000)  NULL,
    [CURRENT_LAND_VALUE]        DECIMAL (17, 2) NULL,
    [CURRENT_IMPROVEMENT_VALUE] DECIMAL (17, 2) NULL,
    [TAX_ASSESSMENT_YEAR]       INT             NULL,
    [YEAR_BUILT]                INT             NULL,
    [TAX_LEVY]                  DECIMAL (17, 2) NULL,
    [NEIGHBOURHOOD_CODE]        VARCHAR (100)   NULL,
    [JurCode]                   VARCHAR (10)    NULL,
    [HashBytes]                 BINARY (64)     NULL,
    [ActionType]                CHAR (1)        NULL,
    [IsDuplicate]               BIT             NULL
);

