CREATE TABLE [StageProcessing].[InternaliAVM] (
    [SourceID]                INT             NULL,
    [Code]                    VARCHAR (200)   NULL,
    [AddressId]               NVARCHAR (510)  NULL,
    [City]                    VARCHAR (200)   NULL,
    [Country]                 VARCHAR (30)    NULL,
    [InsuredValue]            DECIMAL (17, 2) NULL,
    [LegalDescription]        VARCHAR (4000)  NULL,
    [MpacConfidenceLevel]     VARCHAR (50)    NULL,
    [MpacHighConfidenceLimit] VARCHAR (50)    NULL,
    [MpacLowConfidenceLimt]   VARCHAR (50)    NULL,
    [MpacPropertyType]        VARCHAR (50)    NULL,
    [MpacValue]               DECIMAL (17, 2) NULL,
    [OccupancyType]           VARCHAR (50)    NULL,
    [OrderDate]               DATE            NULL,
    [PostalCode]              VARCHAR (50)    NULL,
    [PropertyType]            VARCHAR (200)   NULL,
    [Province]                VARCHAR (50)    NULL,
    [SaleType]                VARCHAR (100)   NULL,
    [StreetName]              VARCHAR (200)   NULL,
    [StreetNumber]            VARCHAR (100)   NULL,
    [StreetType]              VARCHAR (200)   NULL,
    [TeranetValue]            DECIMAL (17, 2) NULL,
    [UnitNumber]              VARCHAR (100)   NULL,
    [ValuePurchasePrice]      DECIMAL (17, 2) NULL,
    [Zoning]                  VARCHAR (400)   NULL,
    [CompleteDate]            DATE            NULL,
    [ActionType]              CHAR (1)        NULL,
    [IsDuplicate]             BIT             NULL
);

