CREATE TABLE [StageProcessing].[InternalMotion] (
    [SourceID]          INT             NULL,
    [Code]              VARCHAR (200)   NULL,
    [UnitNumber]        VARCHAR (100)   NULL,
    [StreetNumber]      VARCHAR (100)   NULL,
    [StreetAddress1]    VARCHAR (200)   NULL,
    [StreetAddress2]    VARCHAR (200)   NULL,
    [Province]          VARCHAR (50)    NULL,
    [City]              VARCHAR (200)   NULL,
    [District]          VARCHAR (100)   NULL,
    [LegalDescription]  VARCHAR (4000)  NULL,
    [IsRenovatedLotNum] VARCHAR (5)     NULL,
    [MetesAndBounds]    VARCHAR (5)     NULL,
    [EstateType]        VARCHAR (50)    NULL,
    [OccupancyType]     VARCHAR (50)    NULL,
    [Zoning]            VARCHAR (400)   NULL,
    [PropertyType]      VARCHAR (200)   NULL,
    [AppraisedValue]    DECIMAL (17, 2) NULL,
    [AddressId]         NVARCHAR (510)  NULL,
    [PropertyIdNumber]  VARCHAR (50)    NULL,
    [Country]           VARCHAR (30)    NULL,
    [PostalCode]        VARCHAR (50)    NULL,
    [ActionType]        CHAR (1)        NULL,
    [IsDuplicate]       BIT             NULL
);

