CREATE TABLE [StageProcessing].[MB_Winnipeg_Assessment_Parcels] (
    [SourceID]                INT             NULL,
    [Code]                    VARCHAR (200)   NULL,
    [Roll Number]             VARCHAR (200)   NULL,
    [Street Number]           VARCHAR (100)   NULL,
    [Unit Number]             VARCHAR (100)   NULL,
    [Street Direction]        VARCHAR (20)    NULL,
    [Street Name]             VARCHAR (200)   NULL,
    [Street Type]             VARCHAR (200)   NULL,
    [Neighbourhood Area]      VARCHAR (200)   NULL,
    [Total Living Area]       DECIMAL (17, 2) NULL,
    [Building Type]           VARCHAR (100)   NULL,
    [Basement]                VARCHAR (20)    NULL,
    [Basement Finish]         VARCHAR (20)    NULL,
    [Year Built]              INT             NULL,
    [Rooms]                   DECIMAL (17, 2) NULL,
    [Air Conditioning]        VARCHAR (20)    NULL,
    [Fire Place]              VARCHAR (20)    NULL,
    [Attached Garage]         VARCHAR (20)    NULL,
    [Detached Garage]         VARCHAR (20)    NULL,
    [Pool]                    VARCHAR (20)    NULL,
    [Number Floors (Condo)]   VARCHAR (100)   NULL,
    [Property Use Code]       VARCHAR (100)   NULL,
    [Assessed Land Area]      DECIMAL (17, 2) NULL,
    [Zoning]                  VARCHAR (400)   NULL,
    [Total Assessed Value]    DECIMAL (17, 2) NULL,
    [Current Assessment Year] INT             NULL,
    [Location]                VARCHAR (50)    NULL,
    [ActionType]              CHAR (1)        NULL,
    [IsDuplicate]             BIT             NULL
);

