CREATE TABLE [StageProcessing].[ON_ALL_FCT_Output] (
    [SourceID]             INT             NULL,
    [Code]                 VARCHAR (200)   NULL,
    [bedroom]              DECIMAL (17, 2) NULL,
    [bedroom_plus]         VARCHAR (20)    NULL,
    [bedroom_string]       VARCHAR (20)    NULL,
    [build_year]           INT             NULL,
    [community_name]       VARCHAR (100)   NULL,
    [condo_exposure]       VARCHAR (20)    NULL,
    [country_name]         VARCHAR (30)    NULL,
    [cross_street]         VARCHAR (100)   NULL,
    [date_end]             DATE            NULL,
    [date_start]           DATE            NULL,
    [date_update]          DATE            NULL,
    [den_front]            VARCHAR (20)    NULL,
    [description1]         VARCHAR (500)   NULL,
    [description2]         VARCHAR (500)   NULL,
    [front_direction]      VARCHAR (20)    NULL,
    [fuel]                 VARCHAR (20)    NULL,
    [furnished]            VARCHAR (20)    NULL,
    [house_style]          VARCHAR (100)   NULL,
    [house_type_name]      VARCHAR (255)   NULL,
    [id]                   NVARCHAR (510)  NULL,
    [included_utility]     VARCHAR (50)    NULL,
    [land]                 DECIMAL (17, 2) NULL,
    [level]                DECIMAL (17, 2) NULL,
    [list_days]            INT             NULL,
    [locker]               VARCHAR (20)    NULL,
    [maintenance]          DECIMAL (17, 2) NULL,
    [ml_num]               VARCHAR (50)    NULL,
    [pool]                 VARCHAR (20)    NULL,
    [price]                DECIMAL (17, 2) NULL,
    [price_sold]           DECIMAL (17, 2) NULL,
    [tax]                  DECIMAL (17, 2) NULL,
    [tax_year]             INT             NULL,
    [washroom]             VARCHAR (20)    NULL,
    [water]                VARCHAR (50)    NULL,
    [amenities.0]          VARCHAR (20)    NULL,
    [amenities.1]          VARCHAR (20)    NULL,
    [amenities.2]          VARCHAR (20)    NULL,
    [amenities.3]          VARCHAR (20)    NULL,
    [amenities.4]          VARCHAR (20)    NULL,
    [house_area.area]      VARCHAR (100)   NULL,
    [house_area.estimate]  DECIMAL (17, 2) NULL,
    [house_area.unit]      VARCHAR (20)    NULL,
    [land.depth]           VARCHAR (50)    NULL,
    [land.front]           VARCHAR (50)    NULL,
    [land.unit]            VARCHAR (50)    NULL,
    [list_status.status]   VARCHAR (50)    NULL,
    [map.lat]              VARCHAR (50)    NULL,
    [map.lon]              VARCHAR (50)    NULL,
    [parking.garage]       VARCHAR (20)    NULL,
    [parking.garage_type]  VARCHAR (20)    NULL,
    [parking.parking]      VARCHAR (20)    NULL,
    [parking.parking_type] VARCHAR (20)    NULL,
    [parking.text]         VARCHAR (50)    NULL,
    [parking.total]        DECIMAL (17, 2) NULL,
    [rooms.0.dc]           VARCHAR (500)   NULL,
    [rooms.0.lv]           DECIMAL (17, 2) NULL,
    [rooms.0.size]         DECIMAL (17, 2) NULL,
    [rooms.0.type]         VARCHAR (20)    NULL,
    [rooms.1.dc]           VARCHAR (500)   NULL,
    [rooms.1.lv]           DECIMAL (17, 2) NULL,
    [rooms.1.size]         DECIMAL (17, 2) NULL,
    [rooms.1.type]         VARCHAR (20)    NULL,
    [rooms.2.dc]           VARCHAR (500)   NULL,
    [rooms.2.lv]           DECIMAL (17, 2) NULL,
    [rooms.2.size]         DECIMAL (17, 2) NULL,
    [rooms.2.type]         VARCHAR (20)    NULL,
    [rooms.3.dc]           VARCHAR (500)   NULL,
    [rooms.3.lv]           DECIMAL (17, 2) NULL,
    [rooms.3.size]         DECIMAL (17, 2) NULL,
    [rooms.3.type]         VARCHAR (20)    NULL,
    [rooms.4.dc]           VARCHAR (500)   NULL,
    [rooms.4.lv]           DECIMAL (17, 2) NULL,
    [rooms.4.size]         DECIMAL (17, 2) NULL,
    [rooms.4.type]         VARCHAR (20)    NULL,
    [rooms.5.dc]           VARCHAR (500)   NULL,
    [rooms.5.lv]           DECIMAL (17, 2) NULL,
    [rooms.5.size]         DECIMAL (17, 2) NULL,
    [rooms.5.type]         VARCHAR (20)    NULL,
    [rooms.6.dc]           VARCHAR (500)   NULL,
    [rooms.6.lv]           DECIMAL (17, 2) NULL,
    [rooms.6.size]         DECIMAL (17, 2) NULL,
    [rooms.6.type]         VARCHAR (20)    NULL,
    [rooms.7.dc]           VARCHAR (500)   NULL,
    [rooms.7.lv]           DECIMAL (17, 2) NULL,
    [rooms.7.size]         DECIMAL (17, 2) NULL,
    [rooms.7.type]         VARCHAR (20)    NULL,
    [rooms.8.dc]           VARCHAR (500)   NULL,
    [rooms.8.lv]           DECIMAL (17, 2) NULL,
    [rooms.8.size]         DECIMAL (17, 2) NULL,
    [rooms.8.type]         VARCHAR (20)    NULL,
    [rooms.9.dc]           VARCHAR (500)   NULL,
    [rooms.9.lv]           DECIMAL (17, 2) NULL,
    [rooms.9.size]         DECIMAL (17, 2) NULL,
    [rooms.9.type]         VARCHAR (20)    NULL,
    [rooms.10.dc]          VARCHAR (500)   NULL,
    [rooms.10.lv]          DECIMAL (17, 2) NULL,
    [rooms.10.size]        DECIMAL (17, 2) NULL,
    [rooms.10.type]        VARCHAR (20)    NULL,
    [rooms.11.dc]          VARCHAR (500)   NULL,
    [rooms.11.lv]          DECIMAL (17, 2) NULL,
    [rooms.11.size]        DECIMAL (17, 2) NULL,
    [rooms.11.type]        VARCHAR (20)    NULL,
    [query.FIELD1]         VARCHAR (100)   NULL,
    [query.FIELD2]         VARCHAR (100)   NULL,
    [query.FIELD3]         VARCHAR (200)   NULL,
    [query.FIELD4]         VARCHAR (200)   NULL,
    [query.FIELD5]         VARCHAR (50)    NULL,
    [query.FIELD6]         VARCHAR (50)    NULL,
    [query.FIELD7]         VARCHAR (50)    NULL,
    [ActionType]           CHAR (1)        NULL,
    [IsDuplicate]          BIT             NULL
);

