CREATE TABLE [StageProcessing].[Residential_Inventory] (
    [SourceID]                INT             NULL,
    [Code]                    VARCHAR (200)   NULL,
    [JurCode]                 VARCHAR (10)    NULL,
    [ARN]                     VARCHAR (200)   NULL,
    [MB Year Built]           INT             NULL,
    [MB Total Finished Area]  DECIMAL (17, 2) NULL,
    [MB Num Storeys]          VARCHAR (100)   NULL,
    [NumberOfWashroom]        VARCHAR (20)    NULL,
    [Num Bedrooms]            DECIMAL (17, 2) NULL,
    [Num Dens]                VARCHAR (20)    NULL,
    [Type of Foundation]      VARCHAR (50)    NULL,
    [ParkingTotal]            DECIMAL (17, 2) NULL,
    [ParkingType]             VARCHAR (20)    NULL,
    [Pool Flag]               VARCHAR (20)    NULL,
    [Other Building Flag]     VARCHAR (20)    NULL,
    [Land Width]              VARCHAR (50)    NULL,
    [Land Depth]              VARCHAR (50)    NULL,
    [Land Sq Measure]         DECIMAL (17, 2) NULL,
    [Land Area]               VARCHAR (50)    NULL,
    [Inc Floor Num]           DECIMAL (17, 2) NULL,
    [Basement Finish Area]    VARCHAR (20)    NULL,
    [Basement Total Area]     VARCHAR (20)    NULL,
    [Deck Sq Footage]         DECIMAL (18)    NULL,
    [Deck Sq Footage Covered] DECIMAL (18)    NULL,
    [FirePlace]               VARCHAR (20)    NULL,
    [Zoning]                  VARCHAR (400)   NULL,
    [HashBytes]               BINARY (64)     NULL,
    [ActionType]              CHAR (1)        NULL,
    [IsDuplicate]             BIT             NULL
);

