CREATE TABLE [StageLanding].[AB_Banff_BuildingPermits] (
    [Roll_No]                       NVARCHAR (MAX) NULL,
    [Application_Year]              NVARCHAR (MAX) NULL,
    [Building_Permit_No]            NVARCHAR (MAX) NULL,
    [Develop__Permit__No]           NVARCHAR (MAX) NULL,
    [Date_Received]                 NVARCHAR (MAX) NULL,
    [Status]                        NVARCHAR (MAX) NULL,
    [Date_Of_Decision]              NVARCHAR (MAX) NULL,
    [Date_Permit_Expires]           NVARCHAR (MAX) NULL,
    [Date_Of_Occupancy_Permit]      NVARCHAR (MAX) NULL,
    [Lot]                           NVARCHAR (MAX) NULL,
    [Block]                         NVARCHAR (MAX) NULL,
    [Plan]                          NVARCHAR (MAX) NULL,
    [Unit_No]                       NVARCHAR (MAX) NULL,
    [Street_No]                     NVARCHAR (MAX) NULL,
    [Street_Name]                   NVARCHAR (MAX) NULL,
    [Building_Name]                 NVARCHAR (MAX) NULL,
    [Business_Name]                 NVARCHAR (MAX) NULL,
    [Description]                   NVARCHAR (MAX) NULL,
    [No_Of_Existing_Dwelling_Units] NVARCHAR (MAX) NULL,
    [No_Of_New_Dweling_Units]       NVARCHAR (MAX) NULL,
    [Value_of_Construction]         NVARCHAR (MAX) NULL,
    [Permit_Fee]                    NVARCHAR (MAX) NULL,
    [SCC_Fee]                       NVARCHAR (MAX) NULL,
    [Comments]                      NVARCHAR (MAX) NULL,
    [Processing_Time]               NVARCHAR (MAX) NULL,
    [SourceID]                      INT            IDENTITY (1, 1) NOT NULL,
    [Code]                          VARCHAR (200)  NULL
);

