CREATE TABLE [StageLanding].[AB_Banff_DevelopmentPermits] (
    [Roll_No]                 NVARCHAR (MAX) NULL,
    [Application_Year]        NVARCHAR (MAX) NULL,
    [Application_No]          NVARCHAR (MAX) NULL,
    [Date_Received]           NVARCHAR (MAX) NULL,
    [Type]                    NVARCHAR (MAX) NULL,
    [Status]                  NVARCHAR (MAX) NULL,
    [Date_Of_Decision]        NVARCHAR (MAX) NULL,
    [Decision_By]             NVARCHAR (MAX) NULL,
    [Date_Permit_Issued]      NVARCHAR (MAX) NULL,
    [Date_Permit_Expires]     NVARCHAR (MAX) NULL,
    [Appeal_No]               NVARCHAR (MAX) NULL,
    [Lot]                     NVARCHAR (MAX) NULL,
    [Block]                   NVARCHAR (MAX) NULL,
    [Plan]                    NVARCHAR (MAX) NULL,
    [Unit_No]                 NVARCHAR (MAX) NULL,
    [Street_No]               NVARCHAR (MAX) NULL,
    [Street_Name]             NVARCHAR (MAX) NULL,
    [Building_Name]           NVARCHAR (MAX) NULL,
    [Business_Name]           NVARCHAR (MAX) NULL,
    [Designer_Architect]      NVARCHAR (MAX) NULL,
    [Development_Type]        NVARCHAR (MAX) NULL,
    [Development_Description] NVARCHAR (MAX) NULL,
    [Fee]                     NVARCHAR (MAX) NULL,
    [Inn_or_home]             NVARCHAR (MAX) NULL,
    [Active]                  NVARCHAR (MAX) NULL,
    [Land_Use_District]       NVARCHAR (MAX) NULL,
    [Comments]                NVARCHAR (MAX) NULL,
    [Planner_Contact]         NVARCHAR (MAX) NULL,
    [SourceID]                INT            IDENTITY (1, 1) NOT NULL,
    [Code]                    VARCHAR (200)  NULL
);

