CREATE TABLE [StageLanding].[AB_Calgary_Building_Permits] (
    [PermitNum]         NVARCHAR (MAX) NULL,
    [StatusCurrent]     NVARCHAR (MAX) NULL,
    [AppliedDate]       NVARCHAR (MAX) NULL,
    [IssuedDate]        NVARCHAR (MAX) NULL,
    [CompletedDate]     NVARCHAR (MAX) NULL,
    [PermitType]        NVARCHAR (MAX) NULL,
    [PermitTypeMapped]  NVARCHAR (MAX) NULL,
    [PermitClass]       NVARCHAR (MAX) NULL,
    [PermitClassGroup]  NVARCHAR (MAX) NULL,
    [PermitClassMapped] NVARCHAR (MAX) NULL,
    [WorkClass]         NVARCHAR (MAX) NULL,
    [WorkClassGroup]    NVARCHAR (MAX) NULL,
    [WorkClassMapped]   NVARCHAR (MAX) NULL,
    [Description]       NVARCHAR (MAX) NULL,
    [HousingUnits]      NVARCHAR (MAX) NULL,
    [EstProjectCost]    NVARCHAR (MAX) NULL,
    [TotalSqFt]         NVARCHAR (MAX) NULL,
    [OriginalAddress]   NVARCHAR (MAX) NULL,
    [CommunityCode]     NVARCHAR (MAX) NULL,
    [CommunityName]     NVARCHAR (MAX) NULL,
    [Latitude]          NVARCHAR (MAX) NULL,
    [Longitude]         NVARCHAR (MAX) NULL,
    [Location]          NVARCHAR (MAX) NULL,
    [LocationCount]     NVARCHAR (MAX) NULL,
    [LocationTypes]     NVARCHAR (MAX) NULL,
    [LocationAddresses] NVARCHAR (MAX) NULL,
    [LocationsWKT]      NVARCHAR (MAX) NULL,
    [LocationsGeoJSON]  NVARCHAR (MAX) NULL,
    [SourceID]          INT            IDENTITY (1, 1) NOT NULL,
    [Code]              VARCHAR (200)  NULL
);

