CREATE TABLE [StageLanding].[ALL_TestAddressFields] (
    [UnitNumber]                NVARCHAR (510) NULL,
    [StreetNumber]              NVARCHAR (510) NULL,
    [StreetName]                NVARCHAR (510) NULL,
    [StreetType]                NVARCHAR (510) NULL,
    [StreetDirection]           NVARCHAR (510) NULL,
    [City]                      NVARCHAR (510) NULL,
    [ProvinceCode]              NVARCHAR (510) NULL,
    [FSA]                       NVARCHAR (510) NULL,
    [District]                  NVARCHAR (510) NULL,
    [JurCode]                   NVARCHAR (510) NULL,
    [Country]                   NVARCHAR (510) NULL,
    [Latitude]                  NVARCHAR (510) NULL,
    [Longitude]                 NVARCHAR (510) NULL,
    [LatitudeLongitude]         NVARCHAR (510) NULL,
    [Neighbourhood]             NVARCHAR (510) NULL,
    [NeighbourhoodDescription]  NVARCHAR (510) NULL,
    [Municipality]              NVARCHAR (510) NULL,
    [Region]                    NVARCHAR (510) NULL,
    [Township]                  NVARCHAR (510) NULL,
    [Range]                     NVARCHAR (510) NULL,
    [LandDistrict]              NVARCHAR (510) NULL,
    [LandDistrictName]          NVARCHAR (510) NULL,
    [AreaDescription]           NVARCHAR (510) NULL,
    [JurDescription]            NVARCHAR (510) NULL,
    [SchoolDistrictDescription] NVARCHAR (510) NULL,
    [CrossStreet]               NVARCHAR (510) NULL,
    [Community]                 NVARCHAR (510) NULL,
    [IsMunicipalAddress]        NVARCHAR (510) NULL,
    [PostalCode]                NVARCHAR (510) NULL,
    [CompleteDate]              NVARCHAR (510) NULL,
    [POSDateSales]              NVARCHAR (510) NULL,
    [ClosingDate]               NVARCHAR (510) NULL,
    [SourceID]                  INT            IDENTITY (1, 1) NOT NULL,
    [Code]                      VARCHAR (200)  NULL
);

