CREATE TABLE [StageLanding].[BC_Langley_Langley_Business_Licenses] (
    [X]                  NVARCHAR (MAX) NULL,
    [Y]                  NVARCHAR (MAX) NULL,
    [PropertyNumber]     NVARCHAR (MAX) NULL,
    [Business_Name]      NVARCHAR (MAX) NULL,
    [Civic_Unit]         NVARCHAR (MAX) NULL,
    [Civic_House]        NVARCHAR (MAX) NULL,
    [Civic_Street]       NVARCHAR (MAX) NULL,
    [Mailing_Address]    NVARCHAR (MAX) NULL,
    [GISLink]            NVARCHAR (MAX) NULL,
    [CommunityName]      NVARCHAR (MAX) NULL,
    [Phone]              NVARCHAR (MAX) NULL,
    [Licence_Desc]       NVARCHAR (MAX) NULL,
    [Category]           NVARCHAR (MAX) NULL,
    [Category_Desc]      NVARCHAR (MAX) NULL,
    [Detail]             NVARCHAR (MAX) NULL,
    [Detail_Desc]        NVARCHAR (MAX) NULL,
    [NAICS_Primary]      NVARCHAR (MAX) NULL,
    [NAICS_Primary_Desc] NVARCHAR (MAX) NULL,
    [Approved_Date]      NVARCHAR (MAX) NULL,
    [Permitted_Use]      NVARCHAR (MAX) NULL,
    [Permitted_Use_Desc] NVARCHAR (MAX) NULL,
    [Seasonal_Employees] NVARCHAR (MAX) NULL,
    [PartTime_Employees] NVARCHAR (MAX) NULL,
    [FullTime_Employees] NVARCHAR (MAX) NULL,
    [Latitude]           NVARCHAR (MAX) NULL,
    [Longitude]          NVARCHAR (MAX) NULL,
    [FID]                NVARCHAR (MAX) NULL,
    [SourceID]           INT            IDENTITY (1, 1) NOT NULL,
    [Code]               VARCHAR (200)  NULL
);

