CREATE TABLE [StageLanding].[BC_Nanaimo_PARCELS] (
    [TYPE]       NVARCHAR (MAX) NULL,
    [HOUSENUMBE] NVARCHAR (MAX) NULL,
    [STREETNAME] NVARCHAR (MAX) NULL,
    [POSTALCODE] NVARCHAR (MAX) NULL,
    [ACCURACY]   NVARCHAR (MAX) NULL,
    [STATUS]     NVARCHAR (MAX) NULL,
    [AREA]       NVARCHAR (MAX) NULL,
    [PLAN]       NVARCHAR (MAX) NULL,
    [PID]        NVARCHAR (MAX) NULL,
    [GISLINK]    NVARCHAR (MAX) NULL,
    [GID]        NVARCHAR (MAX) NULL,
    [ZONING1]    NVARCHAR (MAX) NULL,
    [ZONE1_DESC] NVARCHAR (MAX) NULL,
    [ZONING2]    NVARCHAR (MAX) NULL,
    [ZONE2_DESC] NVARCHAR (MAX) NULL,
    [ZONING3]    NVARCHAR (MAX) NULL,
    [ZONE3_DESC] NVARCHAR (MAX) NULL,
    [ZONING4]    NVARCHAR (MAX) NULL,
    [ZONE4_DESC] NVARCHAR (MAX) NULL,
    [SourceID]   INT            IDENTITY (1, 1) NOT NULL,
    [Code]       VARCHAR (200)  NULL
);

