CREATE TABLE [StageLanding].[BC_Saanich_Parcels] (
    [SUBTYPE]    NVARCHAR (MAX) NULL,
    [JURISDICT]  NVARCHAR (MAX) NULL,
    [FOLIO]      NVARCHAR (MAX) NULL,
    [PID]        NVARCHAR (MAX) NULL,
    [ADDRESS]    NVARCHAR (MAX) NULL,
    [STRUNIT]    NVARCHAR (MAX) NULL,
    [STRNUMBER]  NVARCHAR (MAX) NULL,
    [STRNAME]    NVARCHAR (MAX) NULL,
    [LEGLOT]     NVARCHAR (MAX) NULL,
    [LEGSECTION] NVARCHAR (MAX) NULL,
    [LEGDISTRIC] NVARCHAR (MAX) NULL,
    [LEGPLAN]    NVARCHAR (MAX) NULL,
    [AREASQM]    NVARCHAR (MAX) NULL,
    [AREAHECT]   NVARCHAR (MAX) NULL,
    [SourceID]   INT            IDENTITY (1, 1) NOT NULL,
    [Code]       VARCHAR (200)  NULL
);

