CREATE TABLE [StageLanding].[BC_Surrey_Property_Detail_Listing_2018] (
    [UNIT]               NVARCHAR (MAX) NULL,
    [HOUSE]              NVARCHAR (MAX) NULL,
    [STREET]             NVARCHAR (MAX) NULL,
    [POSTAL_CODE]        NVARCHAR (MAX) NULL,
    [LOT]                NVARCHAR (MAX) NULL,
    [PID]                NVARCHAR (MAX) NULL,
    [FOLIO]              NVARCHAR (MAX) NULL,
    [LOT_TYPE]           NVARCHAR (MAX) NULL,
    [OWNER_TYPE]         NVARCHAR (MAX) NULL,
    [PLAN_NUMBER]        NVARCHAR (MAX) NULL,
    [PLAN_TYPE]          NVARCHAR (MAX) NULL,
    [PLAN_YEAR]          NVARCHAR (MAX) NULL,
    [LOT_SIZE]           NVARCHAR (MAX) NULL,
    [LEGAL_DESCRIPTION]  NVARCHAR (MAX) NULL,
    [ZONE]               NVARCHAR (MAX) NULL,
    [ZONE_DESCRIPTION]   NVARCHAR (MAX) NULL,
    [ZONE_BYLAWS]        NVARCHAR (MAX) NULL,
    [LUC_TEXT]           NVARCHAR (MAX) NULL,
    [LOT_ID]             NVARCHAR (MAX) NULL,
    [ADDRESSID]          NVARCHAR (MAX) NULL,
    [ASSESSMENT_YEAR]    NVARCHAR (MAX) NULL,
    [GROSS_LAND]         NVARCHAR (MAX) NULL,
    [GROSS_IMPROVEMENTS] NVARCHAR (MAX) NULL,
    [GROSS_ASSESSMENT]   NVARCHAR (MAX) NULL,
    [Latitude]           NVARCHAR (MAX) NULL,
    [Longitude]          NVARCHAR (MAX) NULL,
    [LOT_UNITOFMEASURE]  NVARCHAR (MAX) NULL,
    [SourceID]           INT            IDENTITY (1, 1) NOT NULL,
    [Code]               VARCHAR (200)  NULL
);

