CREATE TABLE [StageLanding].[BC_Vancouver_property_tax_report_2018] (
    [PID]                        NVARCHAR (MAX) NULL,
    [LEGAL_TYPE]                 NVARCHAR (MAX) NULL,
    [FOLIO]                      NVARCHAR (MAX) NULL,
    [LAND_COORDINATE]            NVARCHAR (MAX) NULL,
    [ZONE_NAME]                  NVARCHAR (MAX) NULL,
    [ZONE_CATEGORY]              NVARCHAR (MAX) NULL,
    [LOT]                        NVARCHAR (MAX) NULL,
    [BLOCK]                      NVARCHAR (MAX) NULL,
    [PLAN]                       NVARCHAR (MAX) NULL,
    [DISTRICT_LOT]               NVARCHAR (MAX) NULL,
    [FROM_CIVIC_NUMBER]          NVARCHAR (MAX) NULL,
    [TO_CIVIC_NUMBER]            NVARCHAR (MAX) NULL,
    [STREET_NAME]                NVARCHAR (MAX) NULL,
    [PROPERTY_POSTAL_CODE]       NVARCHAR (MAX) NULL,
    [NARRATIVE_LEGAL_LINE1]      NVARCHAR (MAX) NULL,
    [NARRATIVE_LEGAL_LINE2]      NVARCHAR (MAX) NULL,
    [NARRATIVE_LEGAL_LINE3]      NVARCHAR (MAX) NULL,
    [NARRATIVE_LEGAL_LINE4]      NVARCHAR (MAX) NULL,
    [NARRATIVE_LEGAL_LINE5]      NVARCHAR (MAX) NULL,
    [CURRENT_LAND_VALUE]         NVARCHAR (MAX) NULL,
    [CURRENT_IMPROVEMENT_VALUE]  NVARCHAR (MAX) NULL,
    [TAX_ASSESSMENT_YEAR]        NVARCHAR (MAX) NULL,
    [PREVIOUS_LAND_VALUE]        NVARCHAR (MAX) NULL,
    [PREVIOUS_IMPROVEMENT_VALUE] NVARCHAR (MAX) NULL,
    [YEAR_BUILT]                 NVARCHAR (MAX) NULL,
    [BIG_IMPROVEMENT_YEAR]       NVARCHAR (MAX) NULL,
    [TAX_LEVY]                   NVARCHAR (MAX) NULL,
    [NEIGHBOURHOOD_CODE]         NVARCHAR (MAX) NULL,
    [JurCode]                    NVARCHAR (MAX) NULL,
    [SourceID]                   INT            IDENTITY (1, 1) NOT NULL,
    [Code]                       VARCHAR (200)  NULL
);

