CREATE TABLE [StageLanding].[CustomLoad_Commercial_Inventory] (
    [Area]                                                  NVARCHAR (500) NULL,
    [Jurisdiction]                                          NVARCHAR (500) NULL,
    [Roll Number]                                           NVARCHAR (500) NULL,
    [Year Built]                                            NVARCHAR (500) NULL,
    [Effective Year]                                        NVARCHAR (500) NULL,
    [Number of Storeys]                                     NVARCHAR (500) NULL,
    [Gross Leasable Area]                                   NVARCHAR (500) NULL,
    [Net Leasable Area]                                     NVARCHAR (500) NULL,
    [Parking Type – Underground]                            NVARCHAR (500) NULL,
    [Parking Type – Surface]                                NVARCHAR (500) NULL,
    [Parking Type – Parking structure]                      NVARCHAR (500) NULL,
    [Number of Units in an Co-op]                           NVARCHAR (500) NULL,
    [Number of Bachelor Units in a Co-op]                   NVARCHAR (500) NULL,
    [Number of 1 Bedroom Units in a Co-op]                  NVARCHAR (500) NULL,
    [Number of 2 Bedroom Units in a Co-op]                  NVARCHAR (500) NULL,
    [Number of 3 Bedroom Units in a Co-op]                  NVARCHAR (500) NULL,
    [Number of 4 Bedroom Units in a Co-op]                  NVARCHAR (500) NULL,
    [Predominant Manual Class]                              NVARCHAR (MAX) NULL,
    [Gross Building Area]                                   NVARCHAR (500) NULL,
    [Basement Area]                                         NVARCHAR (500) NULL,
    [Strata Industrial / Commercial Lot Area]               NVARCHAR (500) NULL,
    [Apartment – Number of Units]                           NVARCHAR (500) NULL,
    [Apartment – Number of Bachelor Units]                  NVARCHAR (500) NULL,
    [Apartment – Number of 1 Bedroom Units]                 NVARCHAR (500) NULL,
    [Apartment – Number of 2 Bedroom Units]                 NVARCHAR (500) NULL,
    [Apartment – Number of 3 Bedroom Units]                 NVARCHAR (500) NULL,
    [Apartment – Number of 4 Bedroom Units]                 NVARCHAR (500) NULL,
    [Apartment – Number of House Keeping Rooms]             NVARCHAR (500) NULL,
    [Number of Units in a Hotel]                            NVARCHAR (500) NULL,
    [Number of Units in Motel]                              NVARCHAR (500) NULL,
    [Senior Housing – Number of Units]                      NVARCHAR (500) NULL,
    [Senior Housing – Number of Bachelor Units]             NVARCHAR (500) NULL,
    [Senior Housing – Number of 1 Bedrooms]                 NVARCHAR (500) NULL,
    [Senior Housing – Number of 2 Bedrooms]                 NVARCHAR (500) NULL,
    [Senior Housing – Number of 3 Bedrooms]                 NVARCHAR (500) NULL,
    [Senior Housing – Number of Bed Sitting Rooms]          NVARCHAR (500) NULL,
    [Senior Housing – Number of Licensed Care Private Beds] NVARCHAR (500) NULL,
    [Senior Housing – Number of Licensed]                   NVARCHAR (500) NULL,
    [Care Semi-Private Beds]                                NVARCHAR (500) NULL,
    [Total Balcony Area]                                    NVARCHAR (500) NULL,
    [Mezzanine Area]                                        NVARCHAR (500) NULL,
    [Type of Heating]                                       NVARCHAR (500) NULL,
    [Placeholder 1]                                         NVARCHAR (500) NULL,
    [Elevators]                                             NVARCHAR (500) NULL,
    [Type of Construction]                                  NVARCHAR (500) NULL,
    [Other Buildings]                                       NVARCHAR (500) NULL,
    [School District]                                       NVARCHAR (500) NULL,
    [Zoning]                                                NVARCHAR (500) NULL
);

