CREATE TABLE [StageLanding].[CustomLoad_ResidentialInventory] (
    [Area]                       NVARCHAR (500) NULL,
    [Jurisdiction]               NVARCHAR (500) NULL,
    [Roll Number]                NVARCHAR (500) NULL,
    [MB Manual Class]            NVARCHAR (500) NULL,
    [Placeholder 1]              NVARCHAR (500) NULL,
    [Placeholder 2]              NVARCHAR (500) NULL,
    [MB Year Built]              NVARCHAR (500) NULL,
    [MB Effective Year]          NVARCHAR (500) NULL,
    [MB Total Finished Area]     NVARCHAR (500) NULL,
    [MB Num Storeys]             NVARCHAR (500) NULL,
    [Num Full Baths]             NVARCHAR (500) NULL,
    [Num 3-Piece Baths]          NVARCHAR (500) NULL,
    [Num 2-Piece Baths]          NVARCHAR (500) NULL,
    [Num Bedrooms]               NVARCHAR (500) NULL,
    [Num Dens]                   NVARCHAR (500) NULL,
    [Placeholder 3]              NVARCHAR (500) NULL,
    [Type of Foundation]         NVARCHAR (500) NULL,
    [Num Multi Garage]           NVARCHAR (500) NULL,
    [Num Single Garage]          NVARCHAR (500) NULL,
    [Num Carport]                NVARCHAR (500) NULL,
    [Land Characteristic Code 1] NVARCHAR (500) NULL,
    [Land Characteristic Code 2] NVARCHAR (500) NULL,
    [Land Characteristic Code 3] NVARCHAR (500) NULL,
    [Land Characteristic Code 4] NVARCHAR (500) NULL,
    [Land Characteristic Code 5] NVARCHAR (500) NULL,
    [Land Characteristic Code 6] NVARCHAR (500) NULL,
    [Pool Flag]                  NVARCHAR (500) NULL,
    [Other Building Flag]        NVARCHAR (500) NULL,
    [Land Metric Flag]           NVARCHAR (500) NULL,
    [Land Width]                 NVARCHAR (500) NULL,
    [Land Depth]                 NVARCHAR (500) NULL,
    [Land Sq Measure]            NVARCHAR (500) NULL,
    [Land Area]                  NVARCHAR (500) NULL,
    [Placeholder 4]              NVARCHAR (500) NULL,
    [Inc Unit of Measure Value]  NVARCHAR (500) NULL,
    [Inc Unit of Measure Code]   NVARCHAR (500) NULL,
    [Placeholder 5]              NVARCHAR (500) NULL,
    [Inc Floor Num]              NVARCHAR (500) NULL,
    [Inc Effective Year]         NVARCHAR (500) NULL,
    [Plumbing Nil Flag]          NVARCHAR (500) NULL,
    [Basement Finish Area]       NVARCHAR (500) NULL,
    [Basement Total Area]        NVARCHAR (500) NULL,
    [Deck Sq Footage]            NVARCHAR (500) NULL,
    [Deck Sq Footage Covered]    NVARCHAR (500) NULL,
    [Placeholder 6]              NVARCHAR (500) NULL,
    [Fireplace Num 1]            NVARCHAR (500) NULL,
    [Placeholder 7]              NVARCHAR (500) NULL,
    [Fireplace Num 2]            NVARCHAR (500) NULL,
    [Placeholder 8]              NVARCHAR (500) NULL,
    [Fireplace Num 3]            NVARCHAR (500) NULL,
    [Placeholder 9]              NVARCHAR (500) NULL,
    [Fireplace Num 4]            NVARCHAR (500) NULL,
    [Placeholder 10]             NVARCHAR (500) NULL,
    [Fireplace Num 5]            NVARCHAR (500) NULL,
    [First Floor Area]           NVARCHAR (500) NULL,
    [Second Floor Area]          NVARCHAR (500) NULL,
    [Third Floor Area]           NVARCHAR (500) NULL,
    [School District]            NVARCHAR (500) NULL,
    [Zoning]                     NVARCHAR (500) NULL
);

