CREATE TABLE [StageLanding].[InternalMotion] (
    [UnitNumber]        NVARCHAR (510) NULL,
    [StreetNumber]      NVARCHAR (510) NULL,
    [StreetAddress1]    NVARCHAR (510) NULL,
    [StreetAddress2]    NVARCHAR (510) NULL,
    [Province]          NVARCHAR (510) NULL,
    [City]              NVARCHAR (510) NULL,
    [District]          NVARCHAR (510) NULL,
    [LegalDescription]  NVARCHAR (MAX) NULL,
    [IsPartLot]         NVARCHAR (510) NULL,
    [IsRenovatedLotNum] NVARCHAR (510) NULL,
    [MetesAndBounds]    NVARCHAR (510) NULL,
    [EstateType]        NVARCHAR (510) NULL,
    [OccupancyType]     NVARCHAR (510) NULL,
    [Zoning]            NVARCHAR (510) NULL,
    [PropertyType]      NVARCHAR (510) NULL,
    [AppraisedValue]    NVARCHAR (510) NULL,
    [AddressId]         NVARCHAR (510) NULL,
    [PropertyIdNumber]  NVARCHAR (510) NULL,
    [POSDate]           NVARCHAR (510) NULL,
    [Country]           NVARCHAR (510) NULL,
    [PostalCode]        NVARCHAR (510) NULL,
    [SourceId]          NVARCHAR (510) NULL,
    [Code]              NVARCHAR (510) NULL,
    [SourceSystem]      NVARCHAR (510) NULL
);

