CREATE TABLE [StageLanding].[MB_Brandon_Property_Info] (
    [dROLLNMBR]         NVARCHAR (MAX) NULL,
    [STREET_ADDRESS]    NVARCHAR (MAX) NULL,
    [dSHORTLEGAL_1]     NVARCHAR (MAX) NULL,
    [dSHORTLEGAL_2]     NVARCHAR (MAX) NULL,
    [dSHORTLEGAL_3]     NVARCHAR (MAX) NULL,
    [dZONINGCD]         NVARCHAR (MAX) NULL,
    [dSUBDIVISION]      NVARCHAR (MAX) NULL,
    [dNMBRDWELLINGS]    NVARCHAR (MAX) NULL,
    [dYEARBUILT]        NVARCHAR (MAX) NULL,
    [daPROPMEASFRONT_1] NVARCHAR (MAX) NULL,
    [daPROPMEASFRONT_3] NVARCHAR (MAX) NULL,
    [dPROPMEASLOT]      NVARCHAR (MAX) NULL,
    [GROSSTX]           NVARCHAR (MAX) NULL,
    [dHOGAMOUNTCLAIMED] NVARCHAR (MAX) NULL,
    [NETTX]             NVARCHAR (MAX) NULL,
    [TOTAL_VAL]         NVARCHAR (MAX) NULL,
    [PROP_CLASS]        NVARCHAR (MAX) NULL,
    [LAND_GROSS]        NVARCHAR (MAX) NULL,
    [BLDG_GROSS]        NVARCHAR (MAX) NULL,
    [SourceID]          INT            IDENTITY (1, 1) NOT NULL,
    [Code]              VARCHAR (200)  NULL
);

