CREATE TABLE [StageLanding].[MB_Winnipeg_Assessment_Parcels] (
    [Roll Number]                     NVARCHAR (MAX) NULL,
    [Street Number]                   NVARCHAR (MAX) NULL,
    [Unit Number]                     NVARCHAR (MAX) NULL,
    [Street Suffix]                   NVARCHAR (MAX) NULL,
    [Street Direction]                NVARCHAR (MAX) NULL,
    [Street Name]                     NVARCHAR (MAX) NULL,
    [Street Type]                     NVARCHAR (MAX) NULL,
    [Full Address]                    NVARCHAR (MAX) NULL,
    [Neighbourhood Area]              NVARCHAR (MAX) NULL,
    [Market Region]                   NVARCHAR (MAX) NULL,
    [Total Living Area]               NVARCHAR (MAX) NULL,
    [Building Type]                   NVARCHAR (MAX) NULL,
    [Basement]                        NVARCHAR (MAX) NULL,
    [Basement Finish]                 NVARCHAR (MAX) NULL,
    [Year Built]                      NVARCHAR (MAX) NULL,
    [Rooms]                           NVARCHAR (MAX) NULL,
    [Air Conditioning]                NVARCHAR (MAX) NULL,
    [Fire Place]                      NVARCHAR (MAX) NULL,
    [Attached Garage]                 NVARCHAR (MAX) NULL,
    [Detached Garage]                 NVARCHAR (MAX) NULL,
    [Pool]                            NVARCHAR (MAX) NULL,
    [Number Floors (Condo)]           NVARCHAR (MAX) NULL,
    [Property Use Code]               NVARCHAR (MAX) NULL,
    [Assessed Land Area]              NVARCHAR (MAX) NULL,
    [Water Frontage Measurement]      NVARCHAR (MAX) NULL,
    [Sewer Frontage Measurement]      NVARCHAR (MAX) NULL,
    [Property Influences]             NVARCHAR (MAX) NULL,
    [Zoning]                          NVARCHAR (MAX) NULL,
    [Total Assessed Value]            NVARCHAR (MAX) NULL,
    [Total Proposed Assessment Value] NVARCHAR (MAX) NULL,
    [Assessment Date]                 NVARCHAR (MAX) NULL,
    [Detail URL]                      NVARCHAR (MAX) NULL,
    [Current Assessment Year]         NVARCHAR (MAX) NULL,
    [Property Class 1]                NVARCHAR (MAX) NULL,
    [Status 1]                        NVARCHAR (MAX) NULL,
    [Assessed Value 1]                NVARCHAR (MAX) NULL,
    [Property Class 2]                NVARCHAR (MAX) NULL,
    [Status 2]                        NVARCHAR (MAX) NULL,
    [Assessed Value 2]                NVARCHAR (MAX) NULL,
    [Property Class 3]                NVARCHAR (MAX) NULL,
    [Status 3]                        NVARCHAR (MAX) NULL,
    [Assessed Value 3]                NVARCHAR (MAX) NULL,
    [Property Class 4]                NVARCHAR (MAX) NULL,
    [Status 4]                        NVARCHAR (MAX) NULL,
    [Assessed Value 4]                NVARCHAR (MAX) NULL,
    [Property Class 5]                NVARCHAR (MAX) NULL,
    [Status 5]                        NVARCHAR (MAX) NULL,
    [Assessed Value 5]                NVARCHAR (MAX) NULL,
    [Proposed Assessment Year]        NVARCHAR (MAX) NULL,
    [Proposed Assessment Date]        NVARCHAR (MAX) NULL,
    [Proposed Property Class 1]       NVARCHAR (MAX) NULL,
    [Proposed Status 1]               NVARCHAR (MAX) NULL,
    [Proposed Assessment Value 1]     NVARCHAR (MAX) NULL,
    [Proposed Property Class 2]       NVARCHAR (MAX) NULL,
    [Proposed Status 2]               NVARCHAR (MAX) NULL,
    [Proposed Assessment Value 2]     NVARCHAR (MAX) NULL,
    [Proposed Property Class 3]       NVARCHAR (MAX) NULL,
    [Proposed Status 3]               NVARCHAR (MAX) NULL,
    [Proposed Assessment Value 3]     NVARCHAR (MAX) NULL,
    [Proposed Property Class 4]       NVARCHAR (MAX) NULL,
    [Proposed Status 4]               NVARCHAR (MAX) NULL,
    [Proposed Assessment Value 4]     NVARCHAR (MAX) NULL,
    [Proposed Property Class 5]       NVARCHAR (MAX) NULL,
    [Proposed Status 5]               NVARCHAR (MAX) NULL,
    [Proposed Assessment Value 5]     NVARCHAR (MAX) NULL,
    [Multiple Residences]             NVARCHAR (MAX) NULL,
    [Location]                        NVARCHAR (MAX) NULL,
    [SourceID]                        INT            IDENTITY (1, 1) NOT NULL,
    [Code]                            VARCHAR (200)  NULL
);

