CREATE TABLE [StageLanding].[MultiFamily_Commercial_Inventory] (
    [Area]                                                  NVARCHAR (MAX) NULL,
    [Jurisdiction]                                          NVARCHAR (MAX) NULL,
    [Roll Number]                                           NVARCHAR (MAX) NULL,
    [Year Built]                                            NVARCHAR (MAX) NULL,
    [Effective Year]                                        NVARCHAR (MAX) NULL,
    [Number of Storeys]                                     NVARCHAR (MAX) NULL,
    [Gross Leasable Area]                                   NVARCHAR (MAX) NULL,
    [Net Leasable Area]                                     NVARCHAR (MAX) NULL,
    [ParkingTotal]                                          NVARCHAR (MAX) NULL,
    [ParkingType]                                           NVARCHAR (MAX) NULL,
    [NumberOfUnits]                                         NVARCHAR (MAX) NULL,
    [NumberOfBedrooms]                                      NVARCHAR (MAX) NULL,
    [Number of Units in an Co-op]                           NVARCHAR (MAX) NULL,
    [Number of Bachelor Units in a Co-op]                   NVARCHAR (MAX) NULL,
    [Number of 1 Bedroom Units in a Co-op]                  NVARCHAR (MAX) NULL,
    [Number of 2 Bedroom Units in a Co-op]                  NVARCHAR (MAX) NULL,
    [Number of 3 Bedroom Units in a Co-op]                  NVARCHAR (MAX) NULL,
    [Number of 4 Bedroom Units in a Co-op]                  NVARCHAR (MAX) NULL,
    [Predominant Manual Class]                              NVARCHAR (MAX) NULL,
    [Gross Building Area]                                   NVARCHAR (MAX) NULL,
    [Basement Area]                                         NVARCHAR (MAX) NULL,
    [Strata Industrial / Commercial Lot Area]               NVARCHAR (MAX) NULL,
    [Apartment – Number of House Keeping Rooms]             NVARCHAR (MAX) NULL,
    [Number of Units in a Hotel]                            NVARCHAR (MAX) NULL,
    [Number of Units in Motel]                              NVARCHAR (MAX) NULL,
    [Senior Housing – Number of Units]                      NVARCHAR (MAX) NULL,
    [Senior Housing – Number of Bachelor Units]             NVARCHAR (MAX) NULL,
    [Senior Housing – Number of 1 Bedrooms]                 NVARCHAR (MAX) NULL,
    [Senior Housing – Number of 2 Bedrooms]                 NVARCHAR (MAX) NULL,
    [Senior Housing – Number of 3 Bedrooms]                 NVARCHAR (MAX) NULL,
    [Senior Housing – Number of Bed Sitting Rooms]          NVARCHAR (MAX) NULL,
    [Senior Housing – Number of Licensed Care Private Beds] NVARCHAR (MAX) NULL,
    [Senior Housing – Number of Licensed]                   NVARCHAR (MAX) NULL,
    [Care Semi-Private Beds]                                NVARCHAR (MAX) NULL,
    [Total Balcony Area]                                    NVARCHAR (MAX) NULL,
    [Mezzanine Area]                                        NVARCHAR (MAX) NULL,
    [Type of Heating]                                       NVARCHAR (MAX) NULL,
    [Placeholder 1]                                         NVARCHAR (MAX) NULL,
    [Elevators]                                             NVARCHAR (MAX) NULL,
    [Type of Construction]                                  NVARCHAR (MAX) NULL,
    [Other Buildings]                                       NVARCHAR (MAX) NULL,
    [School District]                                       NVARCHAR (MAX) NULL,
    [Zoning]                                                NVARCHAR (MAX) NULL,
    [SourceID]                                              INT            IDENTITY (1, 1) NOT NULL,
    [Code]                                                  VARCHAR (200)  NULL
);

