CREATE TABLE [StageLanding].[ON_Mississauga_2017_Residential_Directory_Townhouse_Complexes] (
    [FID]           NVARCHAR (MAX) NULL,
    [COMPLEX_ID]    NVARCHAR (MAX) NULL,
    [CHAR_Area]     NVARCHAR (MAX) NULL,
    [Z_Area]        NVARCHAR (MAX) NULL,
    [Str_Number]    NVARCHAR (MAX) NULL,
    [StreetName]    NVARCHAR (MAX) NULL,
    [OP_DES]        NVARCHAR (MAX) NULL,
    [Zoning]        NVARCHAR (MAX) NULL,
    [DEV_Name]      NVARCHAR (MAX) NULL,
    [Area_Ha]       NVARCHAR (MAX) NULL,
    [Area_Acre]     NVARCHAR (MAX) NULL,
    [Parking]       NVARCHAR (MAX) NULL,
    [GFA_RES_m2]    NVARCHAR (MAX) NULL,
    [GFARes_ft2]    NVARCHAR (MAX) NULL,
    [GFA_RET_m2]    NVARCHAR (MAX) NULL,
    [GFARet_ft2]    NVARCHAR (MAX) NULL,
    [GFATotalM2]    NVARCHAR (MAX) NULL,
    [GFATot_ft2]    NVARCHAR (MAX) NULL,
    [BLDG_Type]     NVARCHAR (MAX) NULL,
    [Tenure_RES]    NVARCHAR (MAX) NULL,
    [TH_Blocks]     NVARCHAR (MAX) NULL,
    [Storeys]       NVARCHAR (MAX) NULL,
    [RES_Units]     NVARCHAR (MAX) NULL,
    [RET_Units]     NVARCHAR (MAX) NULL,
    [Unit_Ha]       NVARCHAR (MAX) NULL,
    [Unit_Acre]     NVARCHAR (MAX) NULL,
    [FSI]           NVARCHAR (MAX) NULL,
    [Ward_Numbe]    NVARCHAR (MAX) NULL,
    [Shape__Area]   NVARCHAR (MAX) NULL,
    [Shape__Length] NVARCHAR (MAX) NULL,
    [SourceID]      INT            IDENTITY (1, 1) NOT NULL,
    [Code]          VARCHAR (200)  NULL
);

