CREATE TABLE [StageLanding].[Residential_Inventory] (
    [Area]                       NVARCHAR (MAX) NULL,
    [JurCode]                    NVARCHAR (MAX) NULL,
    [ARN]                        NVARCHAR (MAX) NULL,
    [MB Manual Class]            NVARCHAR (MAX) NULL,
    [Placeholder 1]              NVARCHAR (MAX) NULL,
    [Placeholder 2]              NVARCHAR (MAX) NULL,
    [MB Year Built]              NVARCHAR (MAX) NULL,
    [MB Effective Year]          NVARCHAR (MAX) NULL,
    [MB Total Finished Area]     NVARCHAR (MAX) NULL,
    [MB Num Storeys]             NVARCHAR (MAX) NULL,
    [NumberOfWashroom]           NVARCHAR (MAX) NULL,
    [Num Bedrooms]               NVARCHAR (MAX) NULL,
    [Num Dens]                   NVARCHAR (MAX) NULL,
    [Placeholder 3]              NVARCHAR (MAX) NULL,
    [Type of Foundation]         NVARCHAR (MAX) NULL,
    [ParkingTotal]               NVARCHAR (MAX) NULL,
    [ParkingType]                NVARCHAR (MAX) NULL,
    [Land Characteristic Code 1] NVARCHAR (MAX) NULL,
    [Land Characteristic Code 2] NVARCHAR (MAX) NULL,
    [Land Characteristic Code 3] NVARCHAR (MAX) NULL,
    [Land Characteristic Code 4] NVARCHAR (MAX) NULL,
    [Land Characteristic Code 5] NVARCHAR (MAX) NULL,
    [Land Characteristic Code 6] NVARCHAR (MAX) NULL,
    [Pool Flag]                  NVARCHAR (MAX) NULL,
    [Other Building Flag]        NVARCHAR (MAX) NULL,
    [Land Metric Flag]           NVARCHAR (MAX) NULL,
    [Land Width]                 NVARCHAR (MAX) NULL,
    [Land Depth]                 NVARCHAR (MAX) NULL,
    [Land Sq Measure]            NVARCHAR (MAX) NULL,
    [Land Area]                  NVARCHAR (MAX) NULL,
    [Placeholder 4]              NVARCHAR (MAX) NULL,
    [Inc Unit of Measure Value]  NVARCHAR (MAX) NULL,
    [Inc Unit of Measure Code]   NVARCHAR (MAX) NULL,
    [Placeholder 5]              NVARCHAR (MAX) NULL,
    [Inc Floor Num]              NVARCHAR (MAX) NULL,
    [Inc Effective Year]         NVARCHAR (MAX) NULL,
    [Plumbing Nil Flag]          NVARCHAR (MAX) NULL,
    [Basement Finish Area]       NVARCHAR (MAX) NULL,
    [Basement Total Area]        NVARCHAR (MAX) NULL,
    [Deck Sq Footage]            NVARCHAR (MAX) NULL,
    [Deck Sq Footage Covered]    NVARCHAR (MAX) NULL,
    [Placeholder 6]              NVARCHAR (MAX) NULL,
    [FirePlace]                  NVARCHAR (MAX) NULL,
    [Placeholder 7]              NVARCHAR (MAX) NULL,
    [Fireplace Num 2]            NVARCHAR (MAX) NULL,
    [Placeholder 8]              NVARCHAR (MAX) NULL,
    [Fireplace Num 3]            NVARCHAR (MAX) NULL,
    [Placeholder 9]              NVARCHAR (MAX) NULL,
    [Fireplace Num 4]            NVARCHAR (MAX) NULL,
    [Placeholder 10]             NVARCHAR (MAX) NULL,
    [Fireplace Num 5]            NVARCHAR (MAX) NULL,
    [First Floor Area]           NVARCHAR (MAX) NULL,
    [Second Floor Area]          NVARCHAR (MAX) NULL,
    [Third Floor Area]           NVARCHAR (MAX) NULL,
    [School District]            NVARCHAR (MAX) NULL,
    [Zoning]                     NVARCHAR (MAX) NULL,
    [SourceID]                   INT            IDENTITY (1, 1) NOT NULL,
    [Code]                       VARCHAR (200)  NULL
);

